// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GlyphMemoryLeak
{
    internal sealed partial class Vsix
    {
        public const string Id = "GlyphMemoryLeak.b8ec43aa-542c-46de-8489-7cc1eab05a43";
        public const string Name = "GlyphMemoryLeak";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tony Hallett";
        public const string Tags = "";
    }
}
